export { default as Home } from './Home'
export { default as FAQ } from './FAQ'
export { default as TermAndConditions } from './TermAndConditions'
export { default as PrivacyPolicy } from './PrivacyPolicy'
export { default as HireAlumni } from './HireAlumni'
export { default as Curriculum } from './Curriculum'
export { default as AboutUs } from './AboutUs'
export { default as Events } from './Events'
