// USER TYPES
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const LOGOUT = 'LOGOUT';

// NOTE TYPES
export const CREATE_NOTE = 'CREATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const GET_NOTES = 'GET_NOTES';

// STATUS TYPES
export const CREATE_MY_STATUS = 'CREATE_MY_STATUS';
export const GET_MY_STATUS = 'GET_MY_STATUS';
export const GET_MY_FRIENDS_STATUS = 'GET_MY_FRIENDS_STATUS';
export const DELETE_MY_STATUS = 'DELETE_MY_STATUS';

// CHATS TYPES
export const ALT_MESSAGE = 'ALT_MESSAGE';
